### ISSUE TITLE
Todo list calculateur

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#1021]
## Bugs

- [x] Il est impossible de rentrer 0 dans les 12 derniers salaires mensuels bruts

## Modification fonctionnelle

- [x] Il est possible qu'une convention collective permette d'avoir une indemnité malgré la faute grave. Il faut tenir compte de cela lors de la réalisation du parcours. Certaines conventions collectives prévoient aussi une différence entre la faute grave et la faute lourde (indemnité possible ou non).

- [x] Avoir la possibilité de "sortir" d'un parcours d'indemnité conventionnelle: condition non remplie -> message d'erreur et affichage de l'indemnité légale.
- [x] Eviter de demander à trop d'endroit différents le même type d'information ? (e.g. primes / absences etc.)

## Modificiations visuelles

- [ ] Adapter le wording pour etre le plus agnostique possible vis-à-vis de l'utilisateur (s'agit-il d'un salarié ou d'un employeur ?)

- [x] Régler les problème de tailles différentes sur les labels (yes no / Label / currency) (e.g. ancienneté dans la syntec)

- [ ] Trouver d'autres boutons que les boutons "liens" dans le calculateur ?

## Modifications techniques

- [x] Comment gérer les step dynamiques ? Pour le moment, nous donnons le dispatch aux steps. A méditer si une meilleur solution est possible

- [x] Actuellement, nous fournissons plusieurs props au component `Wizard`, notamment `Rules` et `stepReducer` qui sont en fait intrinsèquement liées. On pourrait refléchir à un moyen de combiner les deux.

- [x] A étudier aussi, la combinaison des reducers steps et stepIndex !

https://github.com/SocialGouv/code-du-travail-numerique/pull/1026#issuecomment-513732212
https://github.com/SocialGouv/code-du-travail-numerique/pull/1019#discussion_r302027003

**Comment by Auremie** [comment]
ici @UnbearableBear

**Comment by ClementChapalain** [comment]
j'ajoute le document de @jrduscher sur le sujet ici également :
https://docs.google.com/document/d/1ygLmn-ZYOwgMLfOrcVtGFWihxA9AsLfrHT8003zlmJU/edit

**Comment by ClementChapalain** [comment]
je close pour #1364
