### ISSUE TITLE
Changements orthographe et wording sur tout le site 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1751]
### Description
Je vous propose de centraliser dans cette tâche toutes les fautes d’orthographe repérées sur le site. 
Je vous laisse le soin de modifier/éditer la tâche :)

### Home page

- [x] "Recherchez par mots clefs" à remplacer par "Recherchez par mots-clés"

- [x] "Ex : durée du préavis, indémnité de licenciement" à remplacer par "congés payés, durée du préavis..."

**Nouvelles cartes outils** 
Suite à la nouvelle UI, les cartes outils ne portent plus le nom de simulateur donc changement des noms comme suit : 

- [x] "Simulateur d'indemnités de licenciements" à remplacer par "Indemnité de licenciement"

- [x] "Simulateur de la durée de préavis de licenciement" à remplacer par "Préavis de licenciement"

- [x] "Simulateur de durée de préavis de démission" à remplacer par "Préavis de démission"

- [x] "Simulateur d'embauche" à remplacer par "Salaire brut net" 

- [x] "Simulateur de prime de précarité" à remplacer par "Indemnité de précarité"

- [x] "Modèles de courrier" à remplacer par "Modèles de documents"

**Texte description cartes outils**
Idem suite à la nouvelle UI, les cartes outils comporte le petit texte de description qui est déjà présent dans les cartes de résultat, du coup on en profite également pour faire une repasse dessus comme suit : 

- [x] Pour l'outil "Indemnité de licenciement" : "Simulez simplement le montant d'une indemnité de licenciement en fonction de votre situation" à remplacer par "Estimez le montant de l'indemnité de licenciement"

- [x] Pour l'outil "Préavis de licenciement" : "Estimez simplement la durée du préavis dans le cadre d'un licenciement" à remplacer par "Calculez la durée de préavis de licenciement"

- [x] Pour l'outil "Préavis de démission" : "Connaître la durée du préavis de démission." à remplacer par "Calculez la durée de préavis de démission"

- [x] Pour l'outil "Salaire brut net" : "Estimez le salaire lors d'une embauche : total employeur, brut, net" à remplacer par "Estimez le salaire : brut, net, heures supplémentaires, coût total employeur"

- [x] Pour l'outil "Indemnité de précarité" : "Simulez la prime de précarité d’un salarié." à remplacer par "Estimez le montant de l'indemnité de fin de contrat CDD ou intérim"

- [x] Pour l'outil "Modèles de documents" : "Utilisez des modèles pré-remplis pour vos courriers liés au droit du travail" à remplacer par "Téléchargez et utilisez des modèles de lettres et de documents personnalisables"

- [x] Pour l'outil "Conventions collectives" : "Recherchez une convention collective par Entreprise, SIRET, Nom ou numéro IDCC." à remplacer par "Recherchez une convention collective par son nom, le nom de l'entreprise, le SIRET..."

**Verbe d'action carte outils**
Pour les verbes d'action à mettre sur les cartes : 

- [x] Pour l'outil "Indemnité de licenciement" : on met "Estimer"

- [x] Pour l'outil "Préavis de licenciement" : on met "Calculer"

- [x] Pour l'outil "Préavis de démission" : on met "Calculer"

- [x] Pour l'outil  "Salaire brut net" : on met "Estimer"

- [x] Pour l'outil "Indemnité de précarité" : on met "Calculer"

- [x] Pour l'outil "Modèles de documents" : on met "Découvrir"

- [x] Pour l'outil "Conventions collectives" : on met "Rechercher"

P.S. : Cartes outils à réutiliser dans la page boites à outils

### Outils

- [x] page résultat de tous les outils : il faut rajouter un accent aux e de "Voir le detail du calcul" et "Élements saisis :"

- [x] harmonisation wording des outils : --> sera fait dans une autre tâche, on garde cette tâche pour le reste du site. cf. https://github.com/SocialGouv/code-du-travail-numerique/issues/1834

- [x] Page "Retrouvez tous nos outils" : remplacer "Nos modèles de lettres personnalisables" par "Nos modèles de documents"

### Page Recherchez votre convention collective

"Renseignez le nom de votre entreprise, son SIRET ou le nom de votre convention collective." rajouter à cette phrase un * à côté de SIRET => "Renseignez le nom de votre entreprise, son SIRET* ou le nom de votre convention collective." 

et rajouter en dessous de la phrase une aide concernant le SIRET 
_* Numéro de 14 chiffres correspondant à l'identifiant géographique d'un établissement ou d'une entreprise. Il peut se retrouver sur la fiche de paie._ 

### Page Modèles

- [x] [en page modèles](https://code.travail.gouv.fr/modeles-de-courriers) : remplacer "Les modèles de documents à télécharger" par ""Consulter et télécharger nos modèles de documents"

- [ ] [modification des titres et descriptions](https://github.com/SocialGouv/code-du-travail-numerique/issues/1837)

- [ ] [ ajout d'un disclaimer](https://github.com/SocialGouv/code-du-travail-numerique/issues/1810) sous le bouton télécharger

### Page mentions légales

- [ ] : "quelless que soient leurs générations." à remplacer par "quelles que soient leurs générations."
