### ISSUE TITLE
Mettre en place un pipeline de mise à jour des données

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1849]
on souhaiterai pouvoir mettre à jour les données indépendamment du code source en passant par un pipeline plus léger de mise à jour des données.
- [x] créer des packages avec les données provenants d'api externes
  - [x] kali
  - [x] legi
   - [x] contrib  #2564 
   - [x]  datafiller #2571
     - [x] liste des fiche MT #2571
     - [x] liste des fiche SP #2571 
   - [x] travail-emploi-data
- [x] utiliser l'api  pour récupérer le glossaire, les hightligh et le requete enregistrées #2535
- [x] utiliser l'image nlp comme service afin d'avoir un stage autonome  #2526
- [x] utiliser le package contrib-data
- [x] utiliser le package travail-emploi-data
- [x] utiliser le package datafiller-data
- [x] créer un pipeline de mise à jour  des données

**Comment by lionelB** [comment]
Ce qui manque: 
- [x] Avoir un interface pour gérer les fiches SP 
- [x] Créer une interface pour gérer les fiches MT

**Comment by revolunet** [comment]
Propal :
 - extraire fiches-mt dans un repo dédié + npm
 - publier régulièrement les contribs sur repo + npm : règle le probleme de "vue" côté contrib et l'accès à l'API

**Comment by revolunet** [comment]
- publier régulièrement le datafiller sur npm

**Comment by virginielastisneres** [comment]
@lionelB :) pourrais-tu me dire où tu en es concernant les données du datafiller avec les fiches SP et MT ? 
merciii :)

**Comment by lionelB** [comment]
c'est fait :)

**Comment by virginielastisneres** [comment]
> c'est fait :)

:O ohlalala :) 
Du coup les prochaines étapes (avoir un job séparé ?) j'essaye de me rappeler ce que tu as dis je sais qu'il y a une histoire de job mais je dis peut être des bêtises...

**Comment by lionelB** [comment]
c'est ça, prochaine étape  le pipeline de mise à jour des données :)

**Comment by lionelB** [comment]
- [ ] utilisation du package @socialgouv/contributions-data
- [ ] utilisation du package @socialgouv/datafiller-data

**Comment by lionelB** [comment]
done in #2652  and #2667

**Comment by virginielastisneres** [comment]
Super du coup, on passe en mode automatique tous les soirs à partir de la semaine prochaine ?

**Comment by lionelB** [comment]
yup :)
