### ISSUE TITLE
Finitions UI

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1995]
<details>
<summary>
done
</summary>

### General
- [x] contact services de renseignement -> #1652 
- [x] dédynamiser le header (pour qu'il ne change pas quand on change de page)
- [x] ajouter les icônes sur les tuiles des thèmes
- [x] ajouter les liens dans le footer -> #1974 
- [x] composant background bleu à créer

### HP
- [x] phrase d'intro -> #1973 
- [x] intégrer le svg du hero banner
- [x] ajouter action buttons dans les catégories de la home (outils, thèmes)
- [x] intégrer le svg des thèmes sur la home
- [x] layout section thèmes

### Recherche (Nicolas)
- [x] pas de flèche "consulter" dans la search result pour autre chose que les outils
- [ ] ~~ajouter le thème pour les contributions~~ -> infaisable à l'heure actuelle

### Contenus
- [x] design module de feedback

### Contributions
- [x] ajouter l'encart page personnalisable (avec 2 états selon que la convention soit sélectionnée ou non)
- [x] virer les paddings sur le wrapper en mobile

### Outils
- [x] passer le lien à la ligne -> #1830 
- [x] titres de sections plus petits (cf. design cécile)

### Listing des thèmes
- [x] tuiles thèmes avec icônes et sous-thèmes
- [x] Rajouter un overflow pour ne pas avoir trop de scroll vertical à faire sur mobile

### Page thème
- [x] changer les tuiles thèmes en bouton

### Listing des outils
- [x] enlever les modèles de documents dans cette page
- [x] ajouter une tuile qui renvoie vers la page des modèles de documents et la mettre en premier
- [x] enlever le sous-titre outils

</details>

### Outils #2288 (lionel)
- [x] design mobile période d'absence + temps plein / temps partiel + salaire pour le simulateur (indemnité licenciement et aussi un salaire dans indemnité de précarité, entre autres)
- [x] ajouter la mention `* champs obligatoires`
- [x] état disabled sur le bouton suivant
- issues #2121, #2117
### HP (Manu)
- [x] carrousel en mobile (outils, thèmes)

### Contenus (Manu)
- [x] onglets en carrousel
- [x] articles connexes en dessous du contenu en mobile (aujourd'hui ils sont cachés en mobile)
- [x] blocs documents et liens dans les fiches SP (cf figma 4 Page contenu - encart document)

### Contributions (lionel)
- [x] ajouter thème et breadcrumb dans l'en-tête #2269
- [x] refaire tout le design de la partie `convention collective`

### Recherche (Nicolas)
- [x] bouton orange pour recherche dans le champ de recherche
- [x] ajouter de la marge entre le sous-titre et les résultats
- [x] background bleu sur code du travail et thèmes
- [x] nouveau design actions secondaires (chercher convention, consulter thèmes)
- [x] carrousels code du travail + thèmes en mobile
- [x] remplacer contribution par le theme de la contribution dans les résultats de recherche

### Listing modèles de document #2290 (lionel)
- [x] classer les modèles par thème
- [x] mettre les bonnes tuiles modèles de document
- [x] ajouter les thèmes sur les tuiles modèles de document
- [x] corriger le Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### Page modèle de document  #2286 (lionel)
- [x] revoir l'entête (source = ministère du Travail)
- [x] bouton télécharger en haut à droite du modèle
- [x] enlever titre dans le modèle
- [x] bouton télécharger le modèle
- [x] ajouter format de doc + taille

**Comment by UnbearableBear** [comment]
Tu peux me faire des petites checkboxes s'il te plait ? <3

**Comment by ClementChapalain** [comment]
@UnbearableBear les illustrations de la home et les pictos sont validés ! hésite pas à voir avec cécile si besoin de formats spécifiques

**Comment by ClementChapalain** [comment]
@UnbearableBear j'ai fait une update avec ce qui est prio prio prio pour le 1er janvier

**Comment by ClementChapalain** [comment]
wouhouuuuuuuuuu 🚀

**Comment by UnbearableBear** [comment]
Il faudrait refaire une passe à mon avis il en reste qu'on a raté :)

**Comment by ClementChapalain** [comment]
🙈
