### ISSUE TITLE
Ingest logs in Elastic

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#2440]
Aujourd’hui, les logs sont conservés dans Matomo qui reçoit directement les events du front ou de l’API.

Cela pose quelques problèmes dans le cadre d’une utilisation fréquente et automatisée du contenu des logs :
- Base de données : Matomo n’est pas vraiment prévu pour recevoir des requêtes qui peuvent être franchement lourdes (aggrégations…), et nous ne voulons pas sur-solliciter Matomo, qui devrait rester un outil uniquement dédié à la collecte.
- Structure des données : Matomo conserve les logs tels qu’ils sont envoyés et ne permet pas de les structurer comme on le souhaiterait, avec des index et des aggregations standard, pour faciliter l’accés aux infos dont on a besoin.

Il nous faudrait donc un outil dédié dans lequel seraient stockés les logs (avec ajout quotidien). L’équipe pourrait y accéder ainsi que notre outillage d’analyse automatique. La structure des données serait adaptée à nos besoins.

J’avais commencé à utiliser Logstash pour faire ça, mais j’ai vite passé trop de temps sur la partie admin, et j’ai donc finalement basculé sur des outils pour une analyse en local. Cette solution était suffisante pour le moment, mais ne permet pas de partager les logs et de faire de l’analyse continue / automatique.

La solution minimale serait de déployer une instance de Elastic sur notre Cloud (ou une autre DB) et de l'alimenter quotidiennement dans un format standard en utilisant les dumps de Matomo que l'on stocke déjà (via Logstash ou un script JS).

- [x] Définir solution : #2480 

- [x] Elastic logs : ingester #2557 

- [x]   Elastic logs : instance on Elastic cloud #2558 

- [x] Elastic logs : init query lib #2559 

- [x] Elastic logs : init Kibana dashboard #2560 

- [x] [Monolog v1](https://github.com/SocialGouv/cdtn-monolog/issues/3)

![composants](https://user-images.githubusercontent.com/752778/78140155-d7218200-7429-11ea-9f27-e73501779a58.png)

**Comment by rmelisson** [comment]
ping @revolunet @ClementChapalain voilà, au moins maintenant y'a une issue ! ;)

**Comment by ClementChapalain** [comment]
Merci beaucoup Rémi pour la tâche très claire ! Quelques compléments de mon côté : 
- Matomo n'est effectivement pas utilisable pour l'analyse, car : 
  - Impossible de mettre 2 filtres ou plus sur les événements (par exemple un filtre sur la category et un filtre sur l'action, pour ensuite voir les names)
  - L'outil ne scale dès que l'on demande des données sur un temps trop long (bugs dans l'interface)
  - Impossible d'exporter les données en tableau plat
- L'idéal pour moi serait d'avoir une base qu'on pourrait requêter en SQL, ou une interface permettant de faire des exports agrégés et filtrés

**Comment by UnbearableBear** [comment]
Complètement d'accord ! Même en prod sur CDTN on consulte l'api de matomo pour les pages comme les stats et peut-être même la home avec le contenu populaire (ou pas si tout se fait via le datafiller) donc c'est un besoin qui va vraiment se faire sentir à l'avenir.
@douglasduteil pour faire suite à ce que tu me disais, avoir une base dédiée permettrait de résoudre le pb de caching à la consultation des données

**Comment by revolunet** [comment]
on a de la place sur le cluster ES

**Comment by revolunet** [comment]
@UnbearableBear  quel probleme de caching sur les données ?

**Comment by UnbearableBear** [comment]
@revolunet on est encore en train de voir mais pour la rubrique "contenus populaires" de la homepage, on récupèrerait la data de matomo pour avoir les tendances du mois. Mais hors de question de récupérer ça à chaque chargement de home donc un cache qui se mettrait à jour une fois par jour était envisageable ? J'ai déjà un script qui tourne et qui, en tapant dans l'api de matomo, me sort un score de popularité qui est le produit de la variation du nombre de vues et le nombre de vues.
Sauf que les résultats ne sont pas top (le thème de la démission remonte trop pour l'instant) et il faudrait pouvoir administrer ça via le datafiller. Donc finalement le calcul de la popularité ne se ferait que dans le datafiller pour donner des idées à la personne qui s'occuperait d'éditer tout ça

**Comment by rmelisson** [comment]
https://github.com/SocialGouv/cdtn-monolog/releases/tag/v1.0.0
🍾
