### ISSUE TITLE
Intégration de la charte graphique du gouvernement // Header

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2939]
# Contexte

Le gouvernement a sorti une charte graphique obligatoire et commune à toutes les institutions publiques ayant des conséquences notamment pour les sites web. 

Charte à retrouver ici : https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/introduction

Entre autre, elle réglemente le header des sites web avec de nouveaux logos, taille et position spécifiques. Par conséquent, nous devons intégrer cette charte à notre site et cela a des conséquences sur le header actuel. 

Pour rappel, nous avons 3 types de header en fonction sur le site. 
![Image collée à 2020-8-14 16-21](https://user-images.githubusercontent.com/48682104/90265286-a4b17800-de52-11ea-8355-f3be93aeb66c.png)

# Solution

J'avais commencé une issue avec toutes les versions des 3 pages (version mobile/web et pour chaque sans scroll et avec scroll), j'ai trouvé cela un peu trop chargé. Du coup, j'ai découpé en 3 pour chacune des pages pour éviter des confusions. 

:rotating_light: :rotating_light: :rotating_light: :rotating_light: 
:point_right:  **TOUTES LES MAQUETTES SONT ICI** ===>>> https://www.figma.com/file/Lv4OCQwZ39lVNAZt97cIRP/Untitled?node-id=63%3A341 :tada: :tada: :tada: :tada: :tada: 

- [ ] Pour la Home page #2943

- [ ] Pour la page résultat de recherche #2944

- [ ] Pour toutes les autres pages #2945

**Comment by virginielastisneres** [comment]
❤️
