### ISSUE TITLE
Calculateur indemnités licenciement : centralisation des pistes d'amélioration

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#344]
- [ ] réglementation avant/après: Corriger les références 26 aout, 25 aout..; par : 27 septembre
- [x] ancienneté supérieur à 8 mois et inférieur à 12 mois: possible pour les licenciements prononcés après le 24 septembre.
// oui du coup on a deux dates, mais comme l'avait dit récemment, finalement ce ne sera plus très utile d'ici à l'ouverture au public officielle du service
- [x] corriger le wording [ fautes de frappes dans les messages discriminants)
- [ ] ajout d'une possibilité de "je ne sais pas" si mon entreprise est affiliée + wording #308 
- [x] me relancer pour avoir les tests unitaires ( ca avance mais c'est en xls...)
- [x] ajout du paramètre : inaptitude et indemnité spéciale de licenciement  #310 
- [x] ajout du paramètre impact temps partiel / temps plein ( #131)
- [ ] Ajout métallurgie ; spec in progress - laaaaate - #284 
- [x] ajout de nouvelles conventions collectives #39 
- [x] ajout d'un wording spécifique en page résultat: " Le simulateur ne tient pas compte d'un calcul différent prévu dans le cadre d'un accord d'entreprise et qui vous serait dès lors opposable".
- [x] Construire un graph les indemnités légales et conventionnelles
- [ ] Ancienneté légale minimum nouvelle formule ( 8 mois) : la période doit être interrompue.  Préciser "ancienneté intenterrompue dans le questionnaire. ( dans l'absolu il faudrait le vérifier avec les salaires saisis pour faire le calcul, mais un mois à 0€ peut avoir plein d'autres explications)

**Comment by revolunet** [comment]
toujours d'actu ?
