### ISSUE TITLE
La hiérarchie des balises Hn est incomplète et incohérente sur certaines pages

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3441]
# Retours d'Anne-sophie 

Elle nous indique que "La hiérarchie des titres doit être complète et cohérente. Par exemple sur la page [https://code.travail.gouv.fr/fiche-service-public/arret-maladie-indemnites-journalieres-versees-au-salarie](https://code.travail.gouv.fr/fiche-service-public/arret-maladie-indemnites-journalieres-versees-au-salarie) il manque des titres de niveau 2. 
Il est possible de tester cela avec par exemple l'extension HeadingsMap de Google Chrome. 

# Obligations accessibilité

Je pense qu'il s'agit du critère suivant https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#topic9
![Capture d’écran 2021-04-16 à 11 38 00](https://user-images.githubusercontent.com/48682104/114989226-45f04280-9ea8-11eb-9c11-7815797dd191.png)

Voila la méthodologie des tests associée 
![Capture d’écran 2021-04-16 à 11 39 23](https://user-images.githubusercontent.com/48682104/114989412-733cf080-9ea8-11eb-92c2-d88c172102f8.png)

# Solution attendue

Jonathan a également détecté ce problème et a un fichier complet où sont surlignées en jaune les pages où la hiérarchie est incohérente. S'il y a un questionnement par rapport à une page spécifique voir avec jonathan

=> https://docs.google.com/spreadsheets/d/14DhcTlpmZAv1DWCW18nRwKWx3u-FYSGd/edit?pli=1#gid=1334146039

- [ ] [Page Modèle de document](https://github.com/SocialGouv/code-du-travail-numerique/issues/3462)
- [ ] [Pages internes boite à outils, présentation thèmes et stats](https://github.com/SocialGouv/code-du-travail-numerique/issues/3463)
- [ ] [Page résultat de recherche](https://github.com/SocialGouv/code-du-travail-numerique/issues/3464)
- [ ] [Page navigation dans les thèmes](https://github.com/SocialGouv/code-du-travail-numerique/issues/3465) 
- [ ] Page Widget
- [ ] Page avec accordéon

**Comment by romain-b13** [comment]
Ce problème sera traité dans les issues https://github.com/SocialGouv/code-du-travail-numerique/issues/3516 et https://github.com/SocialGouv/code-du-travail-numerique/issues/3514
