### ISSUE TITLE
Récapitulatif des issues SEO

### ISSUE THREAD

**Issue by Jonathan2051** [SocialGouv/code-du-travail-numerique#3549]
Liste des issues créées à la suite de l'audit SEO mené en avril :

- [x] 1 -  [Absence d'URL canoniques internes (self canonical) ](https://github.com/SocialGouv/code-du-travail-numerique/issues/3487#issue-893077720g)

- [x] 2 - [Absence de balises H2 ](https://github.com/SocialGouv/code-du-travail-numerique/issues/3516#issue-906795790) /!\ il reste quand même des H2 à ajouter aux outils et modèles : https://github.com/SocialGouv/code-du-travail-numerique/issues/3516#issuecomment-1114748566

- [x] 3 - [Les erreurs de balises HN dans la structure](https://github.com/SocialGouv/code-du-travail-numerique/issues/3514#issue-906793846)

- [x] 4 - [Les codes 200 en erreur](https://github.com/SocialGouv/code-du-travail-numerique/issues/3518#issue-906807993)

- [x] 5 - [La présence de liens en nofollow](https://github.com/SocialGouv/code-du-travail-numerique/issues/3517#issue-906797190)

- [x] 6 - [Page d'accueil du CDTN](https://github.com/SocialGouv/code-du-travail-numerique/issues/3519#issue-906810190)

---

- [x] 7 - [Absence des balises Open Graph Protocol](https://github.com/SocialGouv/code-du-travail-numerique/issues/3520#issue-906812041)

- [x] 8 - [Images sans texte alternatif](https://github.com/SocialGouv/code-du-travail-numerique/issues/3521#issue-906813781)

- [ ] 9 - [Les doublons et la taille des balises Title](https://github.com/SocialGouv/code-du-travail-numerique/issues/3505#issue-903506561)

- [x] 10 - [La marque dans la balise Title](https://github.com/SocialGouv/code-du-travail-numerique/issues/3506#issue-903509984)

- [ ] 11 - [Les doublons et la taille des balises meta description](https://github.com/SocialGouv/code-du-travail-numerique/issues/3513#issue-906791723)

- [ ] 12 - [Les doublons de balises H1](https://github.com/SocialGouv/code-du-travail-numerique/issues/3515#issue-906794475)

Ainsi que : 

- [x] 13- Pages des thèmes // Améliorations balises Hn #3465

- [x] 14- Page résultat de recherche : balise incohérente  #3464

- [x] 15- Retirer les H2 non pertients (présents sur toutes les pages) https://github.com/SocialGouv/code-du-travail-numerique/issues/5336

**Comment by romain-b13** [comment]
Est-ce que les issues ci-dessous peuvent être clôturées (si elles sont incluses dans les issues 1 à 12 citées au dessus)  ? 
- https://github.com/SocialGouv/code-du-travail-numerique/issues/3466
- https://github.com/SocialGouv/code-du-travail-numerique/issues/3465
- https://github.com/SocialGouv/code-du-travail-numerique/issues/3464
- https://github.com/SocialGouv/code-du-travail-numerique/issues/3463
- https://github.com/SocialGouv/code-du-travail-numerique/issues/3462
- https://github.com/SocialGouv/code-du-travail-numerique/issues/3441

**Comment by lionelB** [comment]
pour celles qui seront fermées, il faudra penser à citer l'id de l'issue qui reste ouverte afin de faire un lien entre les 2 (notamment si il y a un complément d'infos dans l'issue fermée)

**Comment by Jonathan2051** [comment]
4 _issues_ sur 6 sont à clore car elles font partie de ma liste. Il en reste donc 2 à traiter. Voici le détail 

- #3466 👍 Cf. #3514

- #3465 ❌ A traiter

- #3464 ❌ A traiter

- #3463 👍 Cf. #3514
 
- #3462 👍 Cf. #3514 

- #3441 👍 Cf. #3516 et #3514

**Comment by romain-b13** [comment]
Voir si on ajoute une issue "retirer les H2 non pertinents" (ex : "besoin d'informations")
