### ISSUE TITLE
Convention collective: renommage + fusion

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#4007]
**Fonctionnalité**
Permettre de gérer le changement d'IDCC d'un CC, la création d'une nouvelle CC suite à la fusion de plusieurs CC. 

**Problémes**
Les IDCC 1809 et 1375 ont été renommés.
Les IDCC 2111 et 2395 vont être fusionnés.

**Actions**
Plusieurs points ont été abordés et sont à traiter.

## Outil de contribution

 - [x] Corriger la fonctionnalité d'ajout de CC
 - [x] Lors de l'ajout de la CC, générer les réponses liées aux questions automatiquement
 - [x] Vérifier que l'ajout d'une CC non présente sur legifrance ne pose pas de soucis (récupération d'informations spécifiques)
 - [x] Export des données qui ne remontent pas les CCs renommées (3231 et 3209) (https://github.com/SocialGouv/code-du-travail-numerique/issues/3998)
 
### Recherche globale

 - [x] Ne pas remonter les CCs désactivés dans la recherche (doit déjà être le cas)
 - [x] Identifier des requêtes préqualifiées liées aux anciennes CCs (suite au merge de la 2111 et 2395 vers 3239)

### Page de la Convention collective
 - [x] Ajouter la possibilité d'ajouter un message personnalisée. Ce message pourra être utilisé pour indiquer des changements récents sur la CC (changement de numéro IDCC, fusion...)
 - [x] Ne pas afficher la recherche de CC si pas présente sur legifrance (https://github.com/SocialGouv/code-du-travail-numerique/issues/3996)
 - [x] Migrer les articles liés (covisit) vers les nouvelles CCs.

### Recherche de CC (via "je connais ma convention collective")
 - [x] Recherche d'une IDCC modifiée doit renvoyer la nouvelle IDCC (exemple: si l'utilisateur recherche l'IDCC 1809, ça doit lui retourner la 3231 qui est son nouveau numéro. Idem pour la fusion de la 2111 et 2395 qui retourne 3239)
 - [x] Afficher une information indiquant le changement (ex: IDCC 1809 -> Convention collective départementale des industries métallurgiques, mécaniques, similaires et connexes du Jura (IDCC 3231, ex 1809)

### Page personnalisée
 - [x] Mettre à jour le moteur de recherche comme indiqué dans la section ci-dessus
 - [x] Rediriger les CCs vers leurs nouvelles pages : 1809 -> 3231, 1375 -> 3209 et 2111/2395 -> 3239 (https://github.com/SocialGouv/code-du-travail-numerique/issues/3995)

<img src="https://media.giphy.com/media/PvDM6QHuLPCxi/giphy.gif" />

**Comment by carolineBda** [comment]
Pour la redirection, je penses qu'on peut juste les ajouter ici : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/server/redirects.json

**Comment by m-maillot** [comment]
### Recherche globale

> Identifier des requêtes préqualifiées liées aux anciennes CCs (suite au merge de la 2111 et 3395 vers 3239)

On ne peut pas rechercher une CC dans les prequalified. Identifier pourquoi ? et sinon l'ajouter.

### Page de la Convention collective

> Ajouter la possibilité d'ajouter un message personnalisée. Ce message pourra être utilisé pour indiquer des changements récents sur la CC (changement de numéro IDCC, fusion...)

On ajoute un champ `description` au json de la CC. On l'édite directement dans le json 👨‍💻.

> Ne pas afficher la recherche de CC si pas présente sur legifrance (Module de recherche sur les pages CC : déceptif pour les cc de la métallurgie #3996)

cf : https://github.com/SocialGouv/code-du-travail-numerique/issues/3996#issuecomment-970256541

> Migrer les articles liés (covisit) vers les nouvelles CCs.

@rmelisson @ArmandGiraud y a t il une incidence sur monolog ici ?

### Recherche de CC (via "je connais ma convention collective")

> Recherche d'une IDCC modifiée doit renvoyer la nouvelle IDCC (exemple: si l'utilisateur recherche l'IDCC 1809, ça doit lui retourner la 3231 qui est son nouveau numéro. Idem pour la fusion de la 2111 et 3395 qui retourne 3239)

La recherche se fait dans elasticsearch. La CC renommé va disparaitre et ne va pas ressortir dans les résultats.
L'idée est d'ajouter dans le document elastic l'ancienne IDCC (nouveau champ du document), cela demande une modification de l'ingester-es. Il faut un endroit pour stocker l'ancien IDCC. 
On peut ajouter un champ contenant un tableau d'IDCC liés sur la CC. On le renseigne via l'admin. L'ingester-es le pousse dans le document elasticsearch. On modifie la requête dans la [requête de l'api](https://github.com/SocialGouv/code-du-travail-numerique/blob/25933f55cc07dba39716f0c227834da0c66c419f/packages/code-du-travail-api/src/routes/idcc/idcc.elastic.js) pour inclure ce champ dans la recherche.

> Afficher une information indiquant le changement (ex: IDCC 1809 -> Convention collective départementale des industries métallurgiques, mécaniques, similaires et connexes du Jura (IDCC 3231, ex 1809)

En s'appuyant sur la fonction au dessus, on peut utiliser le tableau d'iDCC liés pour ajouter à la fin (ex. IDCC...)
Sinon, on a la possibilité de le gérer directement dans le frontend avec un if 🤢.

### Page personnalisée 
> Mettre à jour le moteur de recherche comme indiqué dans la section ci-dessus

Cf point dans la recherche CC

> Rediriger les CCs vers leurs nouvelles pages : 1809 -> 3231, 1375 -> 3209 et 2111/3395 -> 3239

La redirection est éphémère.
On utilise le tableau d'IDCC liés de la section `Recherche de CC`. Si on ne trouve pas la contrivution, on recherche l'IDCC dans les tableaux pour identifier le nouvel IDCC et on redirige vers ce dernier.
Sinon, on utilise un redirect en dur dans le frontend (static props) via un tableau définit dans le frontend.

**Comment by m-maillot** [comment]
R&D sur le sujet :

## Ajout d'un texte explicatif personnalisée sur une CC.

- [x] Ajout d'un élément dans le json de la convention collective (depuis l'admin)
- [x] Valider que le contenu est exportée dans l'ingester-es
- [ ] Voir si on l'inclus ou non dans la recherche globale (index elastic)


## Redirection des CC renommées et fusionnées
On va essayer de partir de la [source](https://github.com/SocialGouv/kali-data/blob/master/data/index.json)

- [x] Ajouter l'information que la CC n'est plus disponible
- [x] Ajouter la nouvelle CC
- [x] Ajouter dans le noeud l'ancienne CC, l'information qu'elle a été remplacée par une nouvelle CC. 
- [ ] Lancer l'ingester et valider que les données sont récupérées
- [ ] Regarder le comportement de la recherche de CC. Cette dernière va surement retourner l'ancienne CC, à voir si on peut retourner la nouvelle CC à la place.
- [ ] Du coup, voir pour désactiver la CC dans la recherche. Par contre, cela va la désactiver également dans la recherche de CC. A valider.

Problématiques identifiées:

 * Les pages personnalisées ne sont plus générées par l'ingester-es suite au renommage des CC dans l'outil de contrib. De ce fait, sur le frontend, on va obtenir une erreur 404.
 *

**Comment by m-maillot** [comment]
## Ajout d'un texte explicatif personnalisée sur une CC.

L'ajout d'un champ highlight fonctionne sans grande modification. On peut voir pour améliorer l'admin pour afficher un formulaire plutôt que le json brut.

- [ ] Utiliser un formulaire pour modifier une CC.

**Comment by m-maillot** [comment]
## Information à propos de l'ajout d'une CC

Kali-data est la source de données concernant les conventions collectives. 
Elle est composé d'un fichier `data/index.json` contenant la liste des CCs et leurs statuts. Ainsi que d'un fichier `data/KALICONT****` pour chaque CC contenant les informations de la CC. Ce dernier est récupérer depuis l'api DILA sauf pour les CCs n'ayant pas d'url dans le `data/index.json`.
Il faut donc ajouter ici la CC pour la voir apparaitre dans les données générées par kali-data.

Ensuite l'ingester va alimenter l'admin pour faire apparaitre la nouvelle CC. Il y a un flag `active` mais ce dernier n'est pas utilisé et récupérer par l'ingester dans l'admin.

Ici on a 2 choix :
 * supprimer l'ancienne CC de la liste (n'apparait plus dans l'admin)
 * utiliser le flag active pour gérer son état dans l'admin (demande du dev)

Une fois que l'on a l'information dans l'admin. Ce dernier va être poussé dans elastic. Ce qui permettra au front de retrouver l'information.


Etape de mise en place d'une nouvelle CC : 

- [ ] Il faut mettre à jour le fichier `data/index.json`
Si pas d'url défini (non dispo sur legifrance) 
- [ ] Ajouter un fichier `KALICONT00000*******-IDCC` où `IDCC` est le numéro de la CC et `*******` est l'identifiant du kali de la CC parent référencé sur legifrance
Sinon
- [ ] Le fichier doit être généré automatiquement

**Comment by m-maillot** [comment]
## Recherche

Si besoin d'ajouter des termes spécifiques sur une CC renommer qui manquerai, à la place des préqualifié, il est recommandé d'utiliser les `synonymes`  présent dans le fichier `data/index.json` du dépôt kali-data. Ils sont utilisés pour ajouter des keywords sur les conventions collectives pour la recherche.

**Comment by m-maillot** [comment]
Question à répondre pour préciser la solution à utiliser:

* Notre moteur de recherche doit il être un moteur de recherche de l'état actuel des conventions collectives ou doit il gérer un historique ?
* Si on doit gérer un historique, quelle est la durée de cette historique ?

**Comment by jrduscher** [comment]
### Outil de contribution

- [ ] Réparer la fonction : création de nouvelles questions génériques.
1) Il doit être possible de créer une nouvelle question. 
2) Suite à la création de la question, celle ci doit apparaitre dans les réponses à traiter des conventions collectives, et une réponse générique doit avoir été créée également.

- [ ]  Pour créer une question, ou une CC,  faire en sorte qu'aucune intervention de développeur ne soit nécessaire à l'avenir.
- [ ] Vérifier la stabilité du fonctionnement du flux de veille ( l'état actuel est il pérenne?) 
       - Des alertes ne semblent pas justifiées comme ici : https://contributions.codedutravail.fabrique.social.gouv.fr/admin/answers/90af3e15-05da-4435-963f-2255bdd19b28
       - latences au rafraichissement des articles
- [ ] Tableau de bord: une nouvelle CC dot être ajouté facilement.  Documenter l'action permettant de modifier la sélection de cc apparaissant dans le tableau de bord
- [ ] Réparer un bug d'affichage : le suggester de référence juridique dans les pages réponses apparait sous les champ de saisie ( certaines références sont cachées et ne peuvent pas être sélectionnées)
![image](https://user-images.githubusercontent.com/37538697/144251244-75a6c94d-9fb1-47fb-bcae-c9e1cbe46fc4.png)
### Journée CDTN du 13/12/2021
 - [ ] Amélioration des fonctions de recherche des réponses et réponses génériques : (recherche par l'horodatage )
 - [ ] Création d'un flux de veille dans l'admin pour faire remonter les différences entre le lot en publication sur le cdtn et l'état du stock de réponses dans l'outil de contribution.
 - [ ] S'assurer que l'interface contribution fonctionne et faire l'état des lieux des fonctions à créer pour y parvenir ( simuler une campagne avec des user, unités et cc à traiter, et regarder si le workflow fonctionne correctement. Estimer le coût et les actions nécessaires pour le lancement d'une nouvelle campagne.

**Comment by m-maillot** [comment]
Suite à la discussion de 14h avec Catherine, @romain-b13 et @jrduscher .

On a identifié deux choses :
 * On ne gère pas l'historique
 * On permet une recherche sur des mots clés / IDCC sur d'ancienne CC pour faciliter la recherche des utilisateurs

Catherine va faire une demande pour savoir si le fichier WEEZ sera à jour pour les nouvelles CC (savoir si on doit le gérer ou non de notre coté). Elle fait également une demande pour avoir accès à un fichier de référence pour ne plus l'avoir à le gérer de notre coté.

Un point important a été remonté:
 - [ ] Identifier dans les simulateurs les impacts des nouvelles CCs (@jrduscher )
 - [ ] Modifier les IDCCs des règles sur les simulateurs

**Comment by romain-b13** [comment]
J'ajouterai : 

- [ ] Intégrer la CC 3239 dans les outils : préavis de démission, indemnité de précarité, préavis de licenciement, heures pour recherche d'emploi

**Comment by m-maillot** [comment]
A savoir que le CC 3239 est à mettre en ligne à partir du 1er janvier.

**Comment by romain-b13** [comment]
Les CC **1809** et **1375** ne sont **pas traitées dans nos outils** sauf dans l'outil "indemnité de précarité"
Donc dans les outils : préavis de démission, préavis de licenciement, heures pour recherche d'emploi il n'y a rien à faire, mise à part s'assurer que les nouveaux IDCC (3231 et 3209) apparaissent bien dans la recherche et que quand on les sélectionne elles apparaissent bien comme "CC non traitée"
Pour l'outil "indemnité de précarité", étant donné que les règles ne changent pas avec le renommage, il faudra juste remplacer les idcc 1809 et 1375 par les idcc 3231 et 3209

**Comment by romain-b13** [comment]
A voir si possible avec Ivan (mais ce n'est pas prio) : est-ce que l'outil permettrait de relancer une campagne avec des contributeurs (agents des services de renseignement en région) qui pourraient rédiger des contributions etc.. comme ce qui a été fait au début du projet ?

**Comment by maxgfr** [comment]
@ivangabriele

**Comment by romain-b13** [comment]
Remarque de JR : Comme je sais que vous êtes dessus, je constate que la base d'article du CCN n'est pas la plus à jour (je ne peux pas trouver des articles qui ont été modifiés récemment et qui ont été détectés dans les  alertes de l'admin).

**Comment by jrduscher** [comment]
### Outil de contribution
 
**Tableau de Bord** :
 - [ ] Ajout des contributions génériques au tableau de bord. 
 
Cette amélioration doit permettre de suivre rapidement l'état des réponses génériques, et notamment de vérifier rapidement que les réponses génériques publiées, mises de côté ou en cours de modification. La seule alternative à ce jour consistant à lister l'ensemble des réponses génériques depuis le menu dédié ( il n'ya pas de possibilité de filtres à ce jour).
 
 L'ajout d'un tableau intitulé "Réponses génériques"  entre le tableau 'intitulé "Global" et le tableau intitulé "Conventions collectives".  
 
![image](https://user-images.githubusercontent.com/37538697/147478026-f1bc3e4a-3e80-4aed-8f87-47a80d2759cc.png)

###  Réponses Génériques
 | Nom | A rédiger | En cours de rédaction | A valider | En cours de validation | Validées | Publiées |
 |--|--|--|--|--|--|--|
 |Réponses génériques|-|-|-|-|-|-|
  
 @maxgfr @CaptainConan @romain-b13

**Comment by maxgfr** [comment]
@romain-b13 @m-maillot @carolineBda 
Faudrait voir si on close cette issue, elle devient fat

**Comment by carolineBda** [comment]
> @romain-b13 @m-maillot @carolineBda Faudrait voir si on close cette issue, elle devient fat

Oui exacte on peut re-créer une nouvelle issue avec les trucs qui reste à faire ?
