### ISSUE TITLE
New parcours étape "convention collective" des simulateurs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4049]
## Accessibilité 

**/!\ nous avions convenu que nous traiterions le critère d'accessibilité 7.4 en même temps que le nouveau parcours** :
Pour chaque script qui initie un changement de contexte, l’utilisateur est-il averti ou en a-t-il le contrôle ?
Cf issue #3571 pour laquelle le critère 7.4 a été traité dans la modale de contact téléphonique
A l'étape CC dans le préavis de retraite, lorsque que l'utilisateur commence à taper des lettres, les résultats s'affichent sans action de "lancement" de la recherche de la part de l'utilisateur. Ainsi l'utilisateur utilisant le lecteur d'écran n'est pas averti de l'apparition des résultats.
Voici une solution proposée par Maroua (ayant réalisé l'audit) pour rendre le composant accessible sans ajouter un bouton (bien vérifier l'ajout des role / aria ...et le comportement clavier (Keyboard Support) : 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/grid-combo.html

### 1er écran à l'arrivée sur l'étape CC des simulateurs
![Connaissez-vous votre CC _ Choix 1](https://user-images.githubusercontent.com/84397271/143615363-6d16e703-8137-4d38-84a0-982cc2aec00d.png)

### Parcours je ne souhaite pas renseigner ma CC
![je souhaite passer l'étape](https://user-images.githubusercontent.com/84397271/143615391-74e55674-4df1-4a4f-8bd8-016a3c737ab3.png)

### Parcours je ne connais pas ma CC
![Je ne connais pas ma CC 167](https://user-images.githubusercontent.com/84397271/143616487-aa1f36cc-e0b1-4033-8a6a-2c71f275b729.png)
![Je ne conais pas ma CC 36](https://user-images.githubusercontent.com/84397271/143616500-94380c54-5de6-4b97-94b7-17fd80b3ae8e.png)

**- Si une seule CC est rattachée à l'entreprise sélectionnée**
![Je ne connais pas ma CC 166](https://user-images.githubusercontent.com/84397271/143616502-cd51430a-d597-459e-a488-ad076562553d.png)

**- Si plusieurs CC sont rattachées à l'entreprise sélectionnée**
![Je ne connais pas ma CC 168](https://user-images.githubusercontent.com/84397271/143616492-cd842222-40b4-4448-8529-6174733d9854.png)
![Je ne connais pas ma CC 169](https://user-images.githubusercontent.com/84397271/143616496-c38a4dc1-15e5-4bf9-ba21-95c8afabca1e.png)

### Parcours je connais ma CC
![Je saisi ma CC 5](https://user-images.githubusercontent.com/84397271/143617331-0067b573-f6a1-4357-b1f5-afcecdaae1dc.png)
![Je saisis ma CC 78](https://user-images.githubusercontent.com/84397271/143617315-13e12dcd-f139-4ebf-b1af-6860c7e48d7b.jpg)
![Je saisis ma CC 79](https://user-images.githubusercontent.com/84397271/143617324-fd32073b-7290-4c85-8927-7879d70610c4.png)

## TODO dev

 - [ ] Implémentation du parcours `passer la CC`
 - [ ] Implémentation du parcours `je connais ma CC`
 - [ ] Remise en place des notifications sur les CC traités / non traités
 - [ ] Remise en place du reset du formulaire (cf: https://github.com/SocialGouv/code-du-travail-numerique/pull/4206#discussion_r790639765)
 - [ ] Création d'un proxy sur l'API entreprise pour ajouter le slug (s'appuyer sur l'outil de recherche de sa CC). Via cdtn-api.
 - [ ] Implémentation du parcours `je ne connais pas ma CC`
 - [ ] Implémenter la nouvelle step sur `Préavis de démission`
 - [ ] Implémenter la nouvelle step sur `Heures pour recherche d’emploi`
 - [ ] Implémenter la nouvelle step sur `Préavis de licenciement`
 - [ ] Implémenter la nouvelle step sur `Indemnité de précarité`

**Comment by romain-b13** [comment]
### Events pour le nouveau parcours
Il faut pouvoir tracker le nombre de clics sur les 3 parcours au choix : 
- Je connais ma convention collective. Je la saisis
- Je ne connais pas ma convention collective. Je la recherche
- Je ne souhaite pas renseigner ma convention collective. Je pase l'étape

event_category: "étape CC outil_type_of_users"
event_action: "click_p1" or "click_p2" or "click_p3"
event_name: nom de l'outil

Légende : 
p1 =Je connais ma convention collective. Je la saisis
p2 =Je ne connais pas ma convention collective. Je la recherche
p3 = Je ne souhaite pas renseigner ma convention collective. Je passe l'étape

/!\ ici il faut créer une nouvelle catégorie d'event différente de celle qui a été créee pour l'outil "trouver sa convention collective" qui s'intitule "cc_search_type_of_users"

### Il faut aussi que l'on ait les events suivants : 

**Pour le parcours p1 (1er bouton radio)**

event_category: "cc_search"
event_action: Nom de l'outil
event_name: {"query":"industrie pharmaceutique"} # objet recherche utilisateur

event_category: "cc_select"
event_action: Nom de l'outil
event_name: "idcc44" # numéro de la cc

**Pour le parcours p2 (2ème bouton radio)**

event_category: "enterprise_search"
event_action: Nom de l'outil
event_name: {"address":"","query":"bnp paribas"} # objet

event_category: "enterprise_select"
event_action: Nom de l'outil
event_name: {"label":"JOBTEASER","siren":"508271715"} # objet

il faudrait également créer un nouvel event un peu spécifique : 

event_category: "cc_select_p2_si plusieurs CC pour une entreprise"
event_action: Nom de l'outil
event_name: "idcc44" # numéro de la cc

Cet event est spécifique car dans le parcours P2 icic il n'y a pas de sélection de CC à faire sauf si (et uniquement si) il y a plusieurs CC rattachées à l'entreprise sélectionnée

**Comment by m-maillot** [comment]
Le nouveau formulaire contient des étapes dans la sélection d'une CC. Avant, on avait un moteur de recherche simple. Maintenant, on a un esemble des questions qui entraine l'affichage d'autres champs ou non.

 * je saisi ma convention collective -> Affiche un bloque de recherche sur l'IDCC / nom de la CC. Similaire à ce que l'on a aujourd'hui.
 * je ne connais pas ma convention collective -> On a 2 étapes : recherche de l'entreprise avec 2 champs (nom + code postal) puis sélection de la CC si on en a plusieurs.
 * je ne souhaite pas renseigner ma convention collective -> Passer l'étape mais affiche un message à l'utilisateur.

Il faut pour chaque étape garder les infos sélectionnés sur cette page si l'utilisateur revient dessus. 

Les informations sont actuellement stockées dans le state du formulaire dans le bloc ccn : 

```json
{
  "ccn": {
    "id": "KALICONT000005635886",
    "num": 843,
    "shortTitle": "Boulangerie-pâtisserie (entreprises artisanales)",
    "slug": "843-boulangerie-patisserie-entreprises-artisanales",
    "title": "Boulangerie-pâtisserie (entreprises artisanales)"
  }
}
```

L'idée est de garder ce bloque ccn mais de le modifier pour représenter les 3 états.

On va donc avoir un champ permettant d'identifier l'étape sélectionnée, un champs indiquant la CC sélectionnée, des champs spécifique pour garder les informations saisies.

```json
{
  "ccn": {
    "type": "agreement | enterprise | skipped",
    "enterprise": { // Garde l'entreprise sélectionnée par l'utilisateur.
		"label": "ETABLISSEMENTS DARTY ET FILS", // label retourné par l'API entreprise
		"address": "2 Rue François Ponsard 75016 Paris", // addresse retournée par l'API entreprise, peut être null
        "agreements": [ // liste des CCs liées à l'entreprise récupérée via l'API entreprise
			{
				"id": "KALICONT000005635164",
				"num": 1686,
				"shortTitle": "Commerces et services de l'audiovisuel, de l'électronique et de l'équipement ménager",
				"title": "Convention collective nationale des commerces et services de l'audiovisuel, de l'électronique et de l'équipement ménager du 26 novembre 1992. Etendue par arrêté du 9 mars 1993 JORF 19 mars 1993.",
			}
		],
	},
    "agreement": { // Garde la CC sélectionné par l'utilisateur
      "id": "KALICONT000005635886",
      "num": 843,
      "shortTitle": "Boulangerie-pâtisserie (entreprises artisanales)",
      "slug": "843-boulangerie-patisserie-entreprises-artisanales", // Valider l'utilité de cette donnée car on ne l'a pas quand on passe par la recherche via entreprise.
      "title": "Boulangerie-pâtisserie (entreprises artisanales)"
    }
  }
}
```

**Point à éclaircir:**

#### `type`: utile ? On peut récupérer l'info en regardant si l'on a une CC et/ou une entreprise sélectionnée. 

Je pense qu'il faut le garder. A voir si on gère avec un type complexe grâce à typescript qui permet de contruire les données disponible selon le type.

#### `enterprise.adresse`: On affiche l'adresse sur les screenshots mais l'API nous retourne potentiellement une liste d'adresses. Que fait on quand on a 0 adresse ou plus d'une adresse ?

Point à voir avec @romain-b13 

#### `agreement`: On garde le même format qu'aujourd'hui que l'on descend d'un niveau.

je ne vois pas de point bloquant à ce niveau.

#### `entreprise.agreements`: On ne dispose pas du slug. Valider son utilité dans les simulateurs

Le slug est utilisé sur les simulateurs:
 * Durée de préavis de démaission (page résultat, lien vers la CC)
 * Durée préavis de licenciement (page résultat, lien vers la CC)
 * Heures recherche emploi (page résultat, lien vers la CC)

Sur la recherche de CC, lorsque l'on recherche avec l'entreprise, le lien est construit par le frontend à partir des données retournées par l'API entreprise : 

```js
const getConventionSlug = (convention: AgreementData) =>
  slugify(`${convention.idcc}-${convention.shortTitle}`.substring(0, 80));
```

Je pense que ce mécanisme n'est pas viable. Il se base sur des données retournées par une api externe à CDTN pour créer le slug. Le risque d'avoir un slug erroné est fort.

Je propose de mettre en place une API interne qui gère l'ajout du slug dans l'agreement lorsque l'on recherche une entreprise. L'API serait un proxy sur l'API de l'entreprise.

**Comment by m-maillot** [comment]
Todo : 

- [ ] Modification du state du formulaire (déplacer ccn)
- [ ] Implémentation de la nouvelle step CC
- [ ] Création d'un proxy sur l'API entreprise pour ajouter le slug (s'appuyer sur l'outil de recherche de sa CC). Via cdtn-api.
- [ ] Implémenter la nouvelle step sur tous les outils

**Comment by romain-b13** [comment]
### Messages d'erreur 

**Clic sur suivant sans choisir un des 3 parcours**
![image](https://user-images.githubusercontent.com/84397271/150099410-86819d65-93d5-4a4e-8d5a-293897954b45.png)

**Parcours je ne connais pas ma CC : Clic sur suivant sans avoir sélectionné une entrprise**

![image](https://user-images.githubusercontent.com/84397271/150097378-71ce922d-ca37-4123-a7a9-32dca3e61934.png)

![image](https://user-images.githubusercontent.com/84397271/150097721-fa601bbd-931c-445d-bf21-773b9f200b2f.png)

**Parcours je ne connais pas ma CC et je clic sur suivant sans avoir choisi entre 2 CC proposées pour mon entreprise**

![image](https://user-images.githubusercontent.com/84397271/150099868-894372fa-2ebb-4d3e-a067-e9680c4a5540.png)


**Parcours je connais ma CC : Clic sur suivant sans avoir sélectionné une CC**

![image](https://user-images.githubusercontent.com/84397271/150098496-8d8c1d11-2f82-46fb-b97c-9a47a9113105.png)

![image](https://user-images.githubusercontent.com/84397271/150098687-7ea7f53b-bd95-4fe4-a88d-48d5b748657e.png)


### Clic sur l'aide

**Parcours "je ne connais pas ma CC"**

![image](https://user-images.githubusercontent.com/84397271/150097865-145cba7e-4070-460f-b578-e07d382fc268.png)


**Parcours "je connais ma CC"**

![image](https://user-images.githubusercontent.com/84397271/150098280-d1a8e3ba-831b-464f-80d2-e05b4acb7bc9.png)

**Comment by m-maillot** [comment]
On reste iso avec l'outil de recherche CC : 
<img width="824" alt="image" src="https://user-images.githubusercontent.com/992514/150154445-f77c5107-572d-4902-b545-66c42ea0b4e7.png">

On affiche que le nom de l'entreprise.

**Comment by m-maillot** [comment]
Dans le cas où une CC a déjà été sélectionné avant, on affiche l'écran suivant : 

<img src="https://user-images.githubusercontent.com/84397271/143617324-fd32073b-7290-4c85-8927-7879d70610c4.png" />

**Comment by Armandgrd** [comment]
Je propose (par outil) ça colle avec les autres étapes d’outils:
```
	event_category: "outil"
	event_action: "view_step_préavis “de licenciement
	event_name: ‘cc_type_of_user_p1’
```

**Comment by Armandgrd** [comment]
On envoie les event entreprise_select et `cc_select_px`  au moment du **click suivant** en gardant le format de l'outil trouver sa convention.
CC_select : soit on rempli l'event automatiquement depuis l'entreprise, soit par la selection manuelle faite par l'utilisateur. via le radio button. 

```
event_category: "cc_select_p1" # p1 pour parcours 1: recherche par cc 
event_action: "Nom de l'outil"
event_name: "idcc44" # numéro de la cc
event_value: "2b451f0b-a398-420f-91f6-a1a4be6ed796" # id session
```

**Comment by m-maillot** [comment]
Suite aux 2 messages de @Armandgrd sur les events, on a trouvé une contradiction avec @carolineBda . Ce serait bien d'en discuter.

Voici ce que l'on voit.
Matomo demande 4 champs en entrée : category, action, name et value (cf [la doc](https://hackmd.io/@DfPGKW5TRdSjnarHTPnGaA/ByVFpenSY#Fonctionnement-g%C3%A9n%C3%A9ral))

Sur un simulateur, on va gérer les events comme indiqué dans [la doc](https://hackmd.io/@DfPGKW5TRdSjnarHTPnGaA/ByVFpenSY#Outils) par défaut.

Sur l'outil de recherche sa CC, on va gérer les events comme indiqué dans [la doc](https://hackmd.io/@DfPGKW5TRdSjnarHTPnGaA/ByVFpenSY#Recherche-CC-events-nouveau)

|          | Simulateur                  | Simulateur (CC traitée ou pas)            | Recherche sa CC                         |
|----------|-----------------------------|-------------------------------------------|-----------------------------------------|
| category | outils                      | outils                                    | enterprise_select/enterprise_search/... |
| action   | view_step_Nom du simulateur | cc_select_traitée / cc_select_non_traitée | Trouver sa convention collective        |
| name     | start / info_cc / ...       | IDCC (ex: 3239, 1232...)                  | { query } (quand il y a une requete     |
| value    | N/A                         | N/A                                       | UUID de la session de recherche         |

On a actuellement 3 types d'informations passées.

L'idée ici est d'apporter les actions de la recherche CC dans les simulateurs. Si on garde le même format, il faudrait voir si l'idée est de décaler ou de changer l'action ? 

A discuter de vive voix :) @romain-b13 @FabienRoussel

**Comment by romain-b13** [comment]
### Retours

- [x] **Retirer les 2 messages dans les encadrés bleus mais mettre le premier dans un bouton "help"**

![image](https://user-images.githubusercontent.com/84397271/154654650-fe4f60a7-d64f-4fea-8bb3-b57d911874d0.png)

- **Message quand on sélectionne le parcours "je ne souhaites pas renseigner ma convention collective"**

![image](https://user-images.githubusercontent.com/84397271/154655913-8809530e-9377-4431-9634-1e54cba71abf.png)

- [x]  modifier le texte comme ci-dessous : 
Vous pouvez passer cette étape et poursuivre la simulation qui vous indiquera la durée du préavis prévue par le code du travail. Nous vous recommandons de renseigner votre convention collective qui peut prévoir un préavis plus favorable que celui défini par le code du travail.


- **Message quand la CC sélectionnée n'est pas traitée (message présent dans les 2 premiers parcours)**

![image](https://user-images.githubusercontent.com/84397271/154655117-eb894641-f785-4b2d-84b4-4a08da312e9a.png)

- [x] enlever "à noter" et juste mettre "Convention collective non traitée"

- [x] modifier le message : ci-dessous le nouveau :

La convention collective sélectionnée n'est pas traitée dans ce simulateur.
Vous pouvez tout de même poursuivre la simulation pour connaitre la durée prévue par le code du travail.

- [x] Diminuer l'espacement dans les encadrés "à noter" ou "convention collective non traitée" entre le titre et le corps du texte

![image](https://user-images.githubusercontent.com/84397271/154656905-e75345b8-ac7b-4e64-a8bd-c156df9464bc.png)

- [ ] **Diminuer l'épaisseur du contour lors de la sélection d'une CC ou d'une entreprise** => conserver l'épaisseur que l'on a actuellement lors de la selection d'une CC dans les simulateurs : 

![image](https://user-images.githubusercontent.com/84397271/154666987-402e508f-170a-400e-9477-7d00607e3ad6.png)


- [x] **Diminuer les espacements une fois l'entreprise sélectionnée**

![image](https://user-images.githubusercontent.com/84397271/154672386-765bbc6f-ecf9-4f0e-a5e1-ed406977a0c5.png)

Garder le même espacement que celui qu'on a avant la sélection de l'entreprise : 

![image](https://user-images.githubusercontent.com/84397271/154672729-b53f857e-c21b-4427-b884-b3cac2f8c2c4.png)

- **Inverser les couleurs et changer la taille de police** 

![image](https://user-images.githubusercontent.com/84397271/154673082-926897c3-52cd-42e9-b0e1-b1736a3c3988.png)


![image](https://user-images.githubusercontent.com/84397271/154696445-7d40858a-f120-4e89-8823-b9b25bdcb06f.png)


- [x] "Vous avez sélectionné l'entreprise :" et "Une convention collective a été trouvée pour cette entreprise :" et "3 conventions collectives ont été trouvées pour cette entreprise, sélectionnez la vôtre : " doivent passer en #3E486E et doivent passer en 16 px
- [x] Le nom de la convention collectrive trouvée (dans l'exemple ici il s'agit de "Commerce de détail des fruits et légumes, épicerie et produits laitiers" doit passer en #4D73B8 et doit passer en 16 px

**- j'ajoute également ici les retours qui avaient été faits dans le canal "test branche" :** 

- [x] diminuer la taille de l'encadré lors de la sélection d'une CC ou d'une entreprise, garder la taille des encadrée telle quelle est aujourd'hui lors de la sélection d'une CC dans les simulateurs : 

![image](https://user-images.githubusercontent.com/84397271/154695376-52c0d791-6af4-4160-ac83-4918e1641880.png)

- [x] retirer le scroll vers le haut au moment où on coche un bouton radio quand il ya plusieurs CC pour une entreprise

![image](https://user-images.githubusercontent.com/84397271/154695600-29cba71f-a851-461f-af00-b0978f55a9b5.png)

- [ ] modifier les messages d'erreur tel que ci-dessous 

![image](https://user-images.githubusercontent.com/84397271/154695747-32347338-697d-4735-b49d-c43006b0d170.png)

![image](https://user-images.githubusercontent.com/84397271/154695835-fbb02b6b-7ab1-410d-98af-ca25e3c6b81a.png)

**Comment by romain-b13** [comment]
à voir si on le fait ici : ajd quand on passe la souris sur le mot "convention collective" ce n'est pas une définition qui est affichée mais un renvoi vers la recherche de CC
![image](https://user-images.githubusercontent.com/84397271/154680930-64155f12-2024-462b-bf34-6a760aefe02c.png)

Or dans le glossaire on a bien une définition pour "convention collective" c'est plutôt cette définition qui devrait s'afficher

Si on revient dans le cas du new parcours on devrait avoir un tooltip sur l'expression "convention collectiv" dans la question générale pour ceux qui ne comprennent pas du tout ce à quoi on fait référence : 
![image](https://user-images.githubusercontent.com/84397271/154681244-dd4d2901-62f9-4a08-bb8b-c9ebb5e8872e.png)

Dans la définition du glossaire il faudra aussi que l'on ajoute "En général le nom de votre convention collective est renseigné sur le bulletin de paie.

**Comment by carolineBda** [comment]
@romain-b13 pour "Diminuer l'épaisseur du contour lors de la sélection d'une CC ou d'une entreprise" je ne vois pas la différence avec ce qu'il y a en prod. Pour moi c'est la même épaisseur de trait

**Comment by carolineBda** [comment]
@romain-b13 dans les titres des alertes j'ai aussi enlever le "à noter" pour 
"À noter : convention prochainement traitée"

**Comment by carolineBda** [comment]
@romain-b13 bug liée au tooltip (déjà présent en prod) :
Ici IDCC est surligné mais on ne peux pas cliquer dessus 
![Screenshot from 2022-02-24 11-31-57](https://user-images.githubusercontent.com/4971715/155507990-0806d095-f06c-4b3f-9b1d-501f1cced644.png)
