### ISSUE TITLE
Faire une passe accessibilité sur indemnité de licenciement conventionnelle + sur le dossier licenciement

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4847]
Lien vers l'outil d'accessbilité : https://ara.numerique.gouv.fr/audits/SYI2ZsYiCGDQziOraTfEs/generation

Audit complémentaire de 50 critères à passer sur les 2 outils.

**Comment by carolineBda** [comment]
**TODO**
- [ ] vérifier toutes les images (alt text + description)
- [ ] renommer les noms des images sans les espaces


**Problèmes**
- [ ] contraste lien rouge "modifier"
- [ ] champs formulaire : https://github.com/SocialGouv/code-du-travail-numerique/issues/4855
- [ ] rendre l'html valide : https://github.com/SocialGouv/code-du-travail-numerique/issues/4848
- [ ] navigation tabulation sur les tabs

**Questions**
Pourquoi aria-hidden sur l'infographie : https://code.travail.gouv.fr/information/licenciement-pour-motif-disciplinaire
