### ISSUE TITLE
[meta] Classification des contenus du CDTN

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#627]
meta-tâche regroupant toutes les issues relatives à la classification du contenu CDTN

- [x] créer un système de classification du contenu : #626 
- [x] matcher les autres systèmes de classification (service-public, e-poseidon, etc.) à notre système de classification : #626 
- [x] navigation par thèmes dans le CDTN en utilisant la classification CDTN : #686 
- [ ] apprendre à tagger une requête pour faire ressortir le contenu le plus pertinent lors d'un recherche utilisateur

présentation sur la classification du contenu :
https://docs.google.com/presentation/d/1jCcJi3mCnl7A7fnSlu17oXT73cOgEbL5YNHrxbTpY-Q/edit#slide=id.g5466f0762e_0_0
