### ISSUE TITLE
mise à jour d'ES

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#984]
- [x] update elasticsearch to 7.2 #992 #991 
- [x] update synonyms syntax #982
- [x] explore synonyms graph token filter
- [x] fix match_start_phrase on title to boost document with title that match query #983
- [ ] use an external file for synonyms
